name       : gnome-nibbles
version    : 3.36.1
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-nibbles/3.36/gnome-nibbles-3.36.1.tar.xz : e69781db1dae1f5eb104962fa63e85845b9a77f7a0bae5fa9f4194ec4d94c69e
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
