name       : gnome-nibbles
version    : 3.34.0
release    : 6
source     :
    - https://download.gnome.org/sources/gnome-nibbles/3.34/gnome-nibbles-3.34.0.tar.xz : d61450da8b7ee6f4928330a74c0b670efc4bca4367d36870637d7823a8fd802a
license    : GPL-3.0
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
