name       : gnome-nibbles
version    : 3.38.3
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-nibbles/3.38/gnome-nibbles-3.38.3.tar.xz : 975fde1d83c7b15b392eac7a359161290fc8aeb7605c11e71cee0c3c326b5e61
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(libgnome-games-support-1)
    - desktop-file-utils
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
