name       : gnome-nibbles
version    : 3.24.0
release    : 2
source     :
    - https://github.com/GNOME/gnome-nibbles/archive/3.24.0.tar.gz : da5ed5a8dad8216ce3960c52911c183c639cdcd05082523f40ae390d79d278e5
license    : GPL-3.0
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
