name       : gnome-nibbles
version    : 3.34.1
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-nibbles/3.34/gnome-nibbles-3.34.1.tar.xz : 77f0070af8294ac8795c07982fed4144d581f7336817eb6c6c377bdd370fde59
license    : GPL-3.0
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
