name       : gnome-nibbles
version    : 3.36.0
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-nibbles/3.36/gnome-nibbles-3.36.0.tar.xz : 81a59c11693426e60b4b663ef48c248c997e14e845606e95e52575a1bd647f07
license    : GPL-3.0
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
