name       : gnome-nibbles
version    : 3.31.3
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-nibbles/3.31/gnome-nibbles-3.31.3.tar.xz : 28c41dd55df6ca4cc9d7b00264210adcf82f710981474acee5ac4ff8d4a0e071
license    : GPL-3.0
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
