name       : gnome-nibbles
version    : 3.22.2.2
release    : 1
source     :
    - https://github.com/GNOME/gnome-nibbles/archive/3.22.2.2.tar.gz : 5cc9b600232123af7af2383b4c78c5daa0fd16c16d19000607f94e03b87f5e85
license    : GPL-3.0
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
