name       : gnome-nibbles
version    : 3.38.2
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-nibbles/3.38/gnome-nibbles-3.38.2.tar.xz : 457a64b1c88e2d8d0143c452ffd01f0300d7d3005802954ef5abf9c896b353d9
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Guide a worm around a maze
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(libgnome-games-support-1)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
